packages:
  - .
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.0
  '@types/node': ^22.17.2
  hono: ^4.9.2
  tsx: ^4.20.4
  typescript: ^5.9.2
  valibot: ^1.1.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - leveldown
  - sharp
  - workerd
