packages:
  - .
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.0
  '@hono/valibot-validator': ^0.5.3
  '@rslib/core': ^0.12.2
  '@types/node': ^22.17.2
  '@valibot/to-json-schema': ^1.3.0
  hono: ^4.9.2
  hono-openapi: ^0.4.8
  tsx: ^4.20.4
  typescript: ^5.9.2
  valibot: 1.1.0
  wrangler: ^4.31.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - leveldown
  - sharp
  - workerd
